# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f69eaba43af1235fe34cceeb362cf7f4771252c664b76f0e94b81fd9fe01feef1887a613948558dd0a3e30b6615d615051d49dd741ba64506380da5e7c26d6e

test:
  secret_key_base: 0096b5b2ec3902edf027bf3e17daa021526062c5275cb4214cd01a7e13b6047d3d21cf4ad3b714f50c5ac007f311ec742b8b5474928b7ba9aa369057e7a2ba69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
